### ISSUE TITLE
Routes: /dish (Блюда)

### ISSUE THREAD

**Issue by zlodeev** [yofi2tofi/food-helper-back#3]
### GET
Параметры: 
- `tags - MongoObjectId[]` - для поиска
- `authorId - number` - для страниц авторов
- `sortType - (false|true|null)`
- `favorite - boolean`
- `sortBy - string("favorite"|"pfc"|"price"|"created"|"complexity"|"minutes")` - сортировка по всем полям не нужна, хватит основных исчисляемых
- `limit - number`
- `offset - number`
Ответ:
```js
[{
  "id": number,
  "authorId": number,
  "title": string,
  "coverImgUrl": string,
  "photo": string[], // - url прикрепленных фоток
  "videoUrl": string, // - url или код iframe видоса с ютуба/рутуба
  "favorite": number, // - количество лайков, чтобы не лезть каждый раз в отдельную таблицу с лайками
  "tags": string[],
  "description": markdown?, // - должно хватить функциональности для рецептов
  "price": number, // - приблизительная цифра для ручного ввода
  "proteins": number,
  "elements": [{ elementId,  qty }, ...], // - ингридиенты
  "fats": number,
  "carbohydrates": number,
  "complexity": number[0..10],
  "minutes": number,
  "pfc": () => {}, // - бжд
}, ...]
```

### POST
Параметры: 
```js
{
  "authorId?": number,
  "title": string,
  "coverImgUrl": string,
  "photo?": string[],
  "videoUrl?": string,
  "tags?": string[],
  "description": markdown?, // - должно хватить функциональности для рецептов
  "price?": number, // - приблизительная цифра для ручного ввода
  "elements": [{ elementId,  qty }, ...], // - ингридиенты
  "proteins?": number,
  "fats?": number,
  "carbohydrates?": number,
  "complexity?": number[0..10],
  "minutes?": number,
}
```
Ответ такой же как в геттере, только одиночный

### GET
Параметры: 
- `id - number`

Ответ такой же как в геттере, только одиночный

### PUT
Чекаем по токену authorId чтоб совпадал или на юзере были админские права
Параметры: 
```js
{
  "title?": string,
  "coverImgUrl?": string,
  "photo?": string[],
  "videoUrl?": string,
  "tags?": mongoObject[],
  "description": markdown?, // - должно хватить функциональности для рецептов
  "price?": number, // - приблизительная цифра для ручного ввода
  "elements?": [{ elementId,  qty }, ...], // - ингридиенты
  "proteins?": number,
  "fats?": number,
  "carbohydrates?": number,
  "complexity?": number[0..10],
  "minutes?": number,
}
```
Ответ такой же как в геттере, только одиночный

**Comment by yofi2tofi** [comment]
Надо наверное сделать флаг generalCollection - это те рецепты которые прошли модерацию, они хорошо написаны, красивые фото + видео. Но их может редактировать только админ приложения. И флаг personalCollection - это рецепт чуваков, которые они могут отправлять на модерацию в общую коллекцию, но рецепты из этой коллекции не будут видны в топе рецептом пока не одобрятся в generalCollection, и вот как только он одобряется, пользователь не сможет редактировать такой рецепт, только заявку отправить на изменение чего то.
